---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Add Brew Taps
  homebrew_tap: name={{ item }} state=present
  with_items: taps

- name: Update Homebrew again after taps
  homebrew: update_homebrew=yes

- name: Install brew packages
  homebrew: name={{ item }} state=latest
  with_items: packages

- name: Install pip
  easy_install: name=pip
